name: Build and Publish vesktop-patched-git

on:
  push:
    branches: [main, master]
  repository_dispatch:
    types: [electron-updated]

jobs:
  build:
    runs-on: archlinux
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if triggered by electron-updated and bump pkgrel if needed
        if: github.event_name == 'repository_dispatch' && github.event.action == 'electron-updated'
        run: |
          old_pkgver=$(grep '^pkgver=' PKGBUILD | cut -d'=' -f2)
          old_pkgrel=$(grep '^pkgrel=' PKGBUILD | cut -d'=' -f2)
          # Update sources (simulate what makepkg will do)
          makepkg --nobuild --nodeps --skipinteg --printsrcinfo > .SRCINFO
          new_pkgver=$(grep '^pkgver =' .SRCINFO | head -n1 | awk '{print $3}')
          if [[ "$old_pkgver" == "$new_pkgver" ]]; then
            new_pkgrel=$((old_pkgrel + 1))
            sed -i "s/^pkgrel=.*/pkgrel=$new_pkgrel/" PKGBUILD
            echo "pkgrel bumped to $new_pkgrel"
          else
            sed -i "s/^pkgrel=.*/pkgrel=1/" PKGBUILD
            echo "pkgver changed ($old_pkgver -> $new_pkgver), pkgrel reset to 1."
          fi
        shell: bash

      - name: Build package
        run: |
          sudo pacman -Syu --noconfirm
          makepkg --noconfirm --syncdeps --needed --sign

      - name: Find built package
        id: pkg
        run: |
          PKG=$(ls *.pkg.tar.zst | head -n1)
          echo "pkgfile=$PKG" >> $GITHUB_OUTPUT
          echo "sigfile=$PKG.sig" >> $GITHUB_OUTPUT

      - name: Clone archrepo repository
        uses: actions/checkout@v4
        with:
          repository: Lungooo/archrepo
          path: archrepo
          ssh-key: ${{ secrets.REPO_DEPLOY_KEY }}
          lfs: true

      - name: Add package to repo and sign db
        run: |
          cd archrepo/x86_64
          cp ../../${{ steps.pkg.outputs.pkgfile }} .
          cp ../../${{ steps.pkg.outputs.sigfile }} .
          repo-add --verify --sign --remove lungoo.db.tar.gz *.pkg.tar.zst

      - name: Push repo changes
        run: |
          cd archrepo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          version=$(basename "${{ steps.pkg.outputs.pkgfile }}" | rev | cut -d'-' -f2,3 | rev)
          git commit -m "Updated vesktop-patched-git to Version $version"
          git push
